NehemiahK/Another-React-Lib

- README.md
Just a small edit to the read.me file
> fix documentation 2

- demo/src/index.js
- package-lock.json
- src/GhostButton/GhostButton.css
- src/GhostButton/GhostButton.js
- src/index.js
Adding ghost button with shadow hover effect. Also, adding ghost button to the demo.
> Adding ghost button

- docs/avatar.md
- docs/collapse.md
[#26 ](https://github.com/NehemiahK/Another-React-Lib/issues/26) Adding Avatar and Collapse Documentation
> Update Avatar and Collapse Documentation

- demo/src/index.js
- src/Tabs/tab.css
- src/index.js
Exporting some components and fixing imports in demo page
> Exporting components and fixing imports in demo/index.js

- demo/src/index.js
- src/index.js
> Beautified Demo Page

- src/SocialIcon/SocialIcon.js
This wraps social icons with an anchor tag and passes down a link href as part of #126
> add href to social icons

- src/CircularProgressBar/CircularProgressBar.css
- src/CircularProgressBar/CircularProgressBar.js
Create a circular progress bar component.
> Added progress circle componet

- docs/stickybutton.md
- package-lock.json
#26 Adding StickyButton Documentation.
> Updated the StickyButton documentation

- src/Favourite/Favourite.css
- src/Favourite/Favourite.js
- src/Favourite/Star.js
Hi, @NehemiahK just re-uploaded the Favourite component for [#87](https://github.com/NehemiahK/Another-React-Lib/issues/87)
> Add Favourite component

- CONTRIBUTING.md
> Updated documentation to include CSS class naming guidelines

- docs/alertwrapper.md
- docs/checkbox.md
- src/Checkbox/Checkbox.js
There you go man! I finally made it :smile: 
- Added checkbox docs
- Fixed some typos i found here and there
> Checkbox Docs

- docs/range.md
- src/Range/Range.css
- src/Range/Range.js
- src/Range/useElementEvents.js
- src/Range/usePointerPosition.js
- src/Range/useWindowResize.js
From Issue here:
https://github.com/NehemiahK/Another-React-Lib/issues/44
I also added a doc with some example code in the docs folder. Let me know if anything is amiss.
> Range component

- src/DynamicFooter/DynamicFooter.css
- src/DynamicFooter/DynamicFooter.js
Props: 
Background Color: String
Color: String
> Created Footer with any theme with props

- src/Collapse/Collapse.js
- src/EmailButton/EmailButton.js
- src/ExtraOptions/ExtraOptions.js
- src/Favourite/Favourite.js
- src/TwitterShareButton/twitterShare.js
This PR refactors a few components to use react hooks :fire: and improve prop-types doc
> refactor components

- src/Checkbox/Checkbox.js
fix bug of name in onclick function
> fix bug of onclick checkbox

- src/SearchBar/Searchbar.css
Modified the CSS stylings of the Searchbar component.
> CSS Styling of the Searchbar component

- src/LoadingCardSkeleton/LoadingCardSkeleton.css
- src/LoadingCardSkeleton/LoadingCardSkeleton.js
Props:
height => String/Number
width => String/Number
topImageHeight => String/Number
h3Height => String/Number
pHeight => String/Number
> Created Card Loading Skeleton with props

- src/Card/Card.css
- src/Card/Card.js
HeaderFontColor => String
HeaderFontSize  => String
HeaderFontFamily  => String
Header  => String
subHeaderFontColor  => String
subHeaderFontSize  => String
subHeaderFontFamily  => String
subHeader  => String
dateFontColor  => String
dateFontSize  => String
dateFontFamily  => String
tags => Array
showTags = false,  => Boolean
date  => String
showDate = false,  => Boolean
backgroundImage  => String
borderColor  => String
borderWidth => String/Number
borderRadius  => String/number
onClick  => String
> Created Dymanic Card with design and data props

- docs/card.md
- docs/documentation.md
- src/Card/Card.css
- src/Card/Card.js
- Refactor Card.js
- Introduce proptypes for Card
> Write docs for Card

- src/Checkbox/Checkbox.css
Added animation to make the checkbox appear to 'check' itself when clicked.
It was done using pure css with no changes to the API, so it's backward compatible with anyone who may be using the checkbox already.
I think it looks pretty sweet, and it's the little things with UI components ;)
> added animation to make checkbox 'check'

- demo/src/index.js
- src/Datepicker/Datepicker.css
- src/Datepicker/Datepicker.js
Adds label for datepicker component.
The label text is controlled through prop `label`
I also added support for position the label to the left, right, or top of the datepicker, this is controlled with the prop `labelPosition` and accepts values `left`, `right`, or `top`
> added label for datepicker component

- demo/src/index.js
- src/Stepper/Stepper.css
- src/Stepper/Stepper.js
- src/index.js
Added Stepper component to keep track of steps of a process (i.e. signup or other workflows).
As of now the API supports `steps` and `currentStep`. 
The progress bar updates automatically with `currentStep` changes and is built dynamically by the number of steps.
Currently `steps` defaults to 3 and has a max of 5.
> Stepper Component

- src/ImageGallery/ImageGallery.css
- src/ImageGallery/ImageGallery.js
- src/index.js
Noticed that issue #67 had not been claimed in 12 days so decided to create pull request to address issue.
Sorry for the minor change in index.js I forgot to disable prettier.
> image gallery component created #67
